### ISSUE TITLE
joint face detection

### ISSUE THREAD

**Issue by denghuiru** [FaceDetect/jointCascade_py#1]
Hi, 
I have researched face detection for a period of time and feel very happy that you can release the code  of this paper. However, if I want to get a quick start of this code without training new model, I am not sure what to do, your README.txt also don't specify this. So wil you give a guidance about how to get a quick look of the result of this paper.

**Comment by samuel1208** [comment]
Now it just support the training of that algorithm, and the  test part  is not supported now. Actually you can try to train the model with the readme step by step with AFW dataset(I advice you to train it on AFLW dataset which contain 20000+ faces). I'll release the test part code as soon as possible

**Comment by denghuiru** [comment]
Thanks very much for your answer, I will try to train the model step by step, and at same time looking forward to your test code. 
best regards!

**Comment by samuel1208** [comment]
I have trained a model based on AFW(only contain 337 faces) with 5 non-face images, It just for demo.  Please pull  the latest code

**Comment by denghuiru** [comment]
Hi,
I have run the demo_detect.py on the image pos.jpg, but, Why I can't see the detect result , it seems the code "img.show()" dose not execute. Besides, the run time for a image is so long about 177s, Why the paper said their run time is about 30ms for a image.
Best regards!

**Comment by samuel1208** [comment]
I have comment [here](https://github.com/FaceDetect/jointCascade_py/issues/4)

**Comment by denghuiru** [comment]
@samuel1208  
Thanks to your analysis, We will survey the implementation process in detail. If you have made any progress in optimization, please let us konw. 
Thank you!

**Comment by samuel1208** [comment]
@guo253 @denghuiru  
I have optimized the global regression into trees. This get 10+ speedup, Now the detection speed is about 8s.  I think it still have space to improve the speed.  If you have any advises, please comment it here

**Comment by denghuiru** [comment]
@samuel1208  
Hi, I have tested your new code on my computer, of course, the speed becomes so quickly, Next, I plan to research your code carefully. Besides, I believe if we change the code to C, it will improve the speed at least 10 times, maybe,we can try.

**Comment by samuel1208** [comment]
Yes, but I want to optimize the train speed next. Especially the bootstrap part.  I think achieve the a good benchmark on **FDDB** based on **AFLW** is more  important now. Please let me know any of your progress.  **We can get more ideas via suggesting this project to more people**.

**Comment by denghuiru** [comment]
@samuel1208 
ok, I will deeply research this paper and once we each get some progress, we could let each other know!

**Comment by prayshe** [comment]
I have one questions about building a cart tree. How many training samples used to build a tree? Do you perform random selection on all training samples before building a cart tree? Or you just use the whole data to train one tree?   Thanks!
