### ISSUE TITLE
hello,why can't I find LinearSVR in my sklearn,there is only SVR and nuSVR,thanks.

### ISSUE THREAD

**Issue by guo253** [FaceDetect/jointCascade_py#2]
I replace LinearSVR with SVR,is that all right?
I have already gotten train.model.
My python version is 2.7.

**Comment by samuel1208** [comment]
Bacause the local binary feature is sparse. so it's good and efficient to use LinearSVR. How did you install the sklearn. and What's the version of your sklearn. your can check the version of sklearn via `print sklearn.__version__`. Mine is 0.16.1
