### ISSUE TITLE
random forests

### ISSUE THREAD

**Issue by prayshe** [FaceDetect/jointCascade_py#5]
@samuel1208 
I have one questions about building a cart tree. How many training samples used to build a tree? Do you perform random selection on all training samples before building a cart tree? Or you just use the whole data to train one tree? Thanks!

**Comment by samuel1208** [comment]
The whole data to train one tree

**Comment by prayshe** [comment]
@samuel1208 
Thank for your reply! I want to know whether random sampling is necessary. Besides, the author of that paper said the cart tree is a mix tree, that means some nodes perform classification, and others perform regression. But all nodes on your cart tree just perform the same action determined by the variable, bIsCls. I would appreciate your answer. Thanks!

**Comment by samuel1208** [comment]
Yes. That's different from the paper. Please create an issue for that. and I'll compare this two implementations in the future
